use_tor = true
tor_socks_addr = "127.0.0.1:9050"
interval_secs = 120

sites = [
  "https://google.onion",
  "http://yahoohacks.onion"
]

[org]
domains = [
  "google.com",
  "reddit.com"
]

keywords = [
  "proton",
  "propublica",
  "secure",
  "journalist",
  "leak"
]
